'use strict'

const fs = require('fs/promises')
const { paths } = require('../config')

// wiki/Project Change Evidence.md — generated by .automation/sb-watch.ps1. Only the summary
// table is read: | [[Project]] | Branch | Dirty | HEAD | Latest commit |. The watcher has
// already screened file names for secrets, so nothing here needs re-screening.

function stripLinks (s) {
  return s.replace(/\[\[([^\]|]+)(\|[^\]]+)?\]\]/g, (_, a, b) => (b ? b.slice(1) : a)).trim()
}

async function read () {
  let text
  try {
    text = await fs.readFile(paths.evidence, 'utf8')
  } catch (err) {
    // Optional: without the vault's watcher there are simply no branch chips.
    if (err.code === 'ENOENT') return { ok: true, installed: false, path: paths.evidence, byProject: {} }
    return { ok: false, path: paths.evidence, error: err.code || 'unreadable', byProject: {} }
  }

  const byProject = {}
  let inTable = false

  for (const line of text.split(/\r?\n/)) {
    if (/^\|\s*Project\s*\|/i.test(line)) { inTable = true; continue }
    if (inTable && /^\|[\s:|-]+\|$/.test(line.trim())) continue
    if (inTable && !line.startsWith('|')) break
    if (!inTable || !line.startsWith('|')) continue

    const cells = line.split('|').slice(1, -1).map(c => c.trim())
    if (cells.length < 3) continue

    const name = stripLinks(cells[0])
    const branch = cells[1].replace(/\*\*/g, '')
    const dirty = parseInt(cells[2], 10)
    if (!name) continue

    byProject[name] = {
      branch,
      dirty: Number.isFinite(dirty) ? dirty : 0,
      // "detached at 7ee3a7f" is a flag the board renders in accent, per the anatomy frame.
      flagged: /detach/i.test(branch)
    }
  }

  const scan = text.match(/^Last scan:\s*\*\*(.+?)\*\*/m)
  return { ok: true, path: paths.evidence, byProject, lastScan: scan ? scan[1] : null }
}

module.exports = { read }
